# Generated by Django 4.2.5 on 2023-09-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.CharField(default='na', max_length=4),
        ),
    ]
